### ISSUE TITLE
Images cannot be inserted through WYSIWYG

### ISSUE THREAD

**Issue by sunedepping** [sunedepping/linedepping.dk#2]
It is no longer possible to insert images through the WYSIWYG editor. It shows "false" when clicking on "Source" or saving the page.

Could be related to:
https://drupal.org/node/1956778

**Comment by sunedepping** [comment]
Possible workaround https://drupal.org/comment/7355144#comment-7355144

**Comment by lsolesen** [comment]
I've upgraded WYSIWYG to the latest version. Please test whether that solves your problems?

**Comment by sunedepping** [comment]
Working. 

Mange tak for hjælpen!
